INSERT INTO asociaciones (id,nombre,pais,presidente,siglas) VALUES ('1','Jeep','Italia','Ramiro Cardenaz','JP');
INSERT INTO asociaciones (id,nombre,pais,presidente,siglas) VALUES ('2','WINGS MOBILE','Brasil','Pablo Arias','WB');
INSERT INTO asociaciones (id,nombre,pais,presidente,siglas) VALUES ('3','Adidas','Italia','Daniela Soto','ADD');
INSERT INTO asociaciones (id,nombre,pais,presidente,siglas) VALUES ('4','Angell','Francia','Maximiliano Tota','ALL');
INSERT INTO asociaciones (id,nombre,pais,presidente,siglas) VALUES ('5','Chelo','Portugal','Romario Diaz','CHL');
INSERT INTO asociaciones (id,nombre,pais,presidente,siglas) VALUES ('6','SARA','España','Edwar Gomez','SR');
INSERT INTO asociaciones (id,nombre,pais,presidente,siglas) VALUES ('7','Apex','EEUU','Adam Rillow','APX');
INSERT INTO asociaciones (id,nombre,pais,presidente,siglas) VALUES ('8','Doquer','Argentina','Mariana Rojas','DQ');
INSERT INTO asociaciones (id,nombre,pais,presidente,siglas) VALUES ('9','Pill','Inglaterra','Andrew Pill','PILL');
INSERT INTO asociaciones (id,nombre,pais,presidente,siglas) VALUES ('10','Dinder','Colombia','Joaquin Cadena','DD');

INSERT INTO entrenadores (id,nombre,edad,nacionalidad,correo) VALUES ('1','Jose Rios',35,'Portugues','jrios@gmail.com');
INSERT INTO entrenadores (id,nombre,edad,nacionalidad,correo) VALUES ('2','Camilo Guerrero',40,'Argentino','cguerrero@gmail.com');
INSERT INTO entrenadores (id,nombre,edad,nacionalidad,correo) VALUES ('3','Daniel Martinez',56,'Mexicano','dmartinez@gmail.com');
INSERT INTO entrenadores (id,nombre,edad,nacionalidad,correo) VALUES ('4','Juan Osorio',67,'Colomiano','josorio@gmail.com');
INSERT INTO entrenadores (id,nombre,edad,nacionalidad,correo) VALUES ('5','Hugo Torres',45,'Aleman','htorres@gmail.com');
INSERT INTO entrenadores (id,nombre,edad,nacionalidad,correo) VALUES ('6','Mario Pittano',35,'Italiano','mpittano@gmail.com');
INSERT INTO entrenadores (id,nombre,edad,nacionalidad,correo) VALUES ('7','Javier Zapata',28,'Español','jzapata@gmail.com');
INSERT INTO entrenadores (id,nombre,edad,nacionalidad,correo) VALUES ('8','Maicol Reyes',35,'Canadiense','mreyes@gmail.com');
INSERT INTO entrenadores (id,nombre,edad,nacionalidad,correo) VALUES ('9','Julian Gamboa',49,'Portugues','jgamboa@gmail.com');
INSERT INTO entrenadores (id,nombre,edad,nacionalidad,correo) VALUES ('10','Jose Celis',57,'Mexicano','jcelis@gmail.com');

INSERT INTO jugadores (id,nombre,numero,posicion,nacionalidad) VALUES ('1','Mario Queiroz',35,'Delantero','Argentino');
INSERT INTO jugadores (id,nombre,numero,posicion,nacionalidad) VALUES ('2','Raul Ruiz',2,'Defensa Central','Chileno');
INSERT INTO jugadores (id,nombre,numero,posicion,nacionalidad) VALUES ('3','Cristian Rangel',24,'Defensa Lateral','Ecuador');
INSERT INTO jugadores (id,nombre,numero,posicion,nacionalidad) VALUES ('4','Julian Ortega',7,'Medio campista','Portugues');
INSERT INTO jugadores (id,nombre,numero,posicion,nacionalidad) VALUES ('5','Rene Ordoñez',21,'Media punta','Belga');
INSERT INTO jugadores (id,nombre,numero,posicion,nacionalidad) VALUES ('6','Sebastian Lopez',11,'Segunda punta','Ruso');
INSERT INTO jugadores (id,nombre,numero,posicion,nacionalidad) VALUES ('7','Javier Casillo',45,'Extremo','Japones');
INSERT INTO jugadores (id,nombre,numero,posicion,nacionalidad) VALUES ('8','Andres Pirlo',5,'Pivote','Colombiano');
INSERT INTO jugadores (id,nombre,numero,posicion,nacionalidad) VALUES ('9','Daniel Carrillo',99,'Interior derecho','Frances');
INSERT INTO jugadores (id,nombre,numero,posicion,nacionalidad) VALUES ('10','Felipe Salamanca',33,'Interior Izquierdo','Chileno');

INSERT INTO competiciones (id,nombre,fechainicio,fechafin,montopremio) VALUES('1','Champhions','2023-03-01','2024-02-05',100000000);
INSERT INTO competiciones (id,nombre,fechainicio,fechafin,montopremio) VALUES('2','Libertadores','2022-11-02','2023-01-15',50000000);
INSERT INTO competiciones (id,nombre,fechainicio,fechafin,montopremio) VALUES('3','Copa Oro','2023-05-01','2023-10-15',25000000);
INSERT INTO competiciones (id,nombre,fechainicio,fechafin,montopremio) VALUES('4','LIga B','2022-02-15','2022-11-01',37000000);
INSERT INTO competiciones (id,nombre,fechainicio,fechafin,montopremio) VALUES('5','Copa Clubes Internacional','2022-07-12','2022-08-17',45000000);
INSERT INTO competiciones (id,nombre,fechainicio,fechafin,montopremio) VALUES('6','Liga Aguila','2022-01-29','2022-06-15',40000000);
INSERT INTO competiciones (id,nombre,fechainicio,fechafin,montopremio) VALUES('7','UEFA','2023-03-04','2023-08-08',75000000);
INSERT INTO competiciones (id,nombre,fechainicio,fechafin,montopremio) VALUES('8','Copa AICON','2022-12-04','2023-01-24',1100000);
INSERT INTO competiciones (id,nombre,fechainicio,fechafin,montopremio) VALUES('9','Copa Claro','2022-02-15','2022-07-07',2300000);
INSERT INTO competiciones (id,nombre,fechainicio,fechafin,montopremio) VALUES('10','Copa Gloria','2022-04-19','2022-08-22',2700000);
